"""
Gate 70C -- Render AI Bank Package Preview v1

Generates static HTML preview pages for student and teacher payloads.

Usage:
  .venv-ingest\\Scripts\\python.exe tools\\ai\\render_gate70c_ai_bank_package_preview_v1.py

Output:
  data/ai/package_candidates/static_preview/gate70c_student_preview.html
  data/ai/package_candidates/static_preview/gate70c_teacher_preview.html
"""

import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

STUDENT_FILE  = ROOT / "data" / "ai" / "package_candidates" / "gate70c_student_payload_v1.json"
TEACHER_FILE  = ROOT / "data" / "ai" / "package_candidates" / "gate70c_teacher_payload_v1.json"
PREVIEW_DIR   = ROOT / "data" / "ai" / "package_candidates" / "static_preview"
STUDENT_HTML  = PREVIEW_DIR / "gate70c_student_preview.html"
TEACHER_HTML  = PREVIEW_DIR / "gate70c_teacher_preview.html"

print("Gate 70C -- Render AI Bank Package Preview v1")
print("=" * 60)

_BASE_CSS = """
body{font-family:Georgia,serif;max-width:820px;margin:40px auto;padding:0 24px;line-height:1.6;color:#222}
h1{font-size:1.6rem;border-bottom:2px solid #333;padding-bottom:8px}
h2{font-size:1.1rem;color:#444;margin-top:32px}
.resource{border:1px solid #ddd;border-radius:6px;padding:20px;margin:24px 0;background:#fafafa}
.resource h3{font-size:1rem;margin:0 0 8px}
.tag{display:inline-block;font-size:.75rem;padding:2px 8px;border-radius:12px;margin-right:6px;font-family:monospace}
.tag-ok{background:#d4edda;color:#155724}
.tag-warn{background:#fff3cd;color:#856404}
.prompt-box{background:#fff;border:1px solid #ccc;border-radius:4px;padding:12px;margin:12px 0;white-space:pre-wrap;font-family:monospace;font-size:.9rem}
.rubric li{margin:4px 0}
.meta{font-size:.78rem;color:#777;margin-top:8px}
.banner{background:#fffbea;border:1px solid #f0c040;border-radius:6px;padding:12px 16px;margin-bottom:24px}
"""

def _tag(text: str, ok: bool = True) -> str:
    cls = "tag-ok" if ok else "tag-warn"
    return f'<span class="tag {cls}">{html.escape(text)}</span>'


def _build_student_card(res: dict) -> str:
    title = html.escape(res.get("title", "Untitled"))
    topic = html.escape(res.get("topic", ""))
    rtype = html.escape(res.get("resource_type", "question"))
    diff  = html.escape(res.get("difficulty", "medium"))
    mins  = res.get("estimated_time_minutes", 10)
    instr = html.escape(res.get("student_instructions", ""))
    prompt = html.escape(res.get("student_prompt", ""))
    return f"""
<div class="resource">
  <h3>{title}</h3>
  {_tag(rtype)} {_tag(diff)} {_tag(f'{mins} min')}
  <p class="meta">Topic: {topic}</p>
  <h2>Instructions</h2>
  <p>{instr}</p>
  <h2>Question</h2>
  <div class="prompt-box">{prompt}</div>
</div>"""


def _build_teacher_card(res: dict) -> str:
    title     = html.escape(res.get("title", "Untitled"))
    topic     = html.escape(res.get("topic", ""))
    rtype     = html.escape(res.get("resource_type", "question"))
    diff      = html.escape(res.get("difficulty", "medium"))
    mins      = res.get("estimated_time_minutes", 10)
    prompt    = html.escape(res.get("student_prompt", ""))
    answer    = html.escape(res.get("answer_key", ""))
    notes     = html.escape(res.get("teacher_notes", ""))
    provider  = html.escape(res.get("provider", "mock"))
    model     = html.escape(res.get("model", "mock"))
    prov      = res.get("provenance", {})
    rubric    = res.get("marking_rubric", [])
    rubric_html = "".join(
        f"<li>[{html.escape(str(r.get('marks','?')))}m] {html.escape(r.get('criterion',''))} — "
        f"<em>{html.escape(r.get('guidance',''))}</em></li>"
        for r in rubric
    )
    return f"""
<div class="resource">
  <h3>{title} [TEACHER VIEW]</h3>
  {_tag(rtype)} {_tag(diff)} {_tag(f'{mins} min')}
  {_tag(f'provider: {provider}')} {_tag(f'model: {model}')}
  <p class="meta">Topic: {topic}</p>
  <h2>Student Question</h2>
  <div class="prompt-box">{prompt}</div>
  <h2>Answer Key</h2>
  <div class="prompt-box">{answer}</div>
  <h2>Marking Rubric</h2>
  <ul class="rubric">{rubric_html}</ul>
  <h2>Teacher Notes</h2>
  <p>{notes}</p>
  <p class="meta">
    gate70b_approved: {_tag('yes', prov.get('gate70b_approved', False))}
    no_raw_source_text: {_tag('yes', prov.get('no_raw_source_text_used', False))}
    teacher_review_required: {_tag('yes', prov.get('teacher_review_required', False))}
  </p>
</div>"""


def _render(title: str, payload: dict, card_fn) -> str:
    banner = """
<div class="banner">
  <strong>AI-Generated Content — Teacher Review Required</strong><br>
  This content was generated by an AI model and has been approved by a teacher reviewer.
  It must be verified by the publishing teacher before use with students.
  <br><strong>Auto-publish: disabled &nbsp;|&nbsp; Supabase write: not performed</strong>
</div>"""
    cards = "".join(card_fn(r) for r in payload.get("resources", []))
    n     = len(payload.get("resources", []))
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<style>{_BASE_CSS}</style>
</head>
<body>
<h1>{html.escape(title)}</h1>
<p>Package: {html.escape(payload.get('package_id',''))}  &nbsp;|&nbsp;  Resources: {n}</p>
{banner}
{cards}
</body>
</html>"""


PREVIEW_DIR.mkdir(parents=True, exist_ok=True)

if not STUDENT_FILE.exists() or not TEACHER_FILE.exists():
    print("ERROR: payloads not found — run export_gate70c_ai_bank_package_payloads_v1.py first")
    sys.exit(1)

student_payload = json.loads(STUDENT_FILE.read_text(encoding="utf-8"))
teacher_payload = json.loads(TEACHER_FILE.read_text(encoding="utf-8"))

STUDENT_HTML.write_text(
    _render("Gate 70C — Student Preview", student_payload, _build_student_card),
    encoding="utf-8",
)
TEACHER_HTML.write_text(
    _render("Gate 70C — Teacher Preview (Confidential)", teacher_payload, _build_teacher_card),
    encoding="utf-8",
)

print(f"Student preview: {STUDENT_HTML.relative_to(ROOT)}")
print(f"Teacher preview: {TEACHER_HTML.relative_to(ROOT)}")
print("Status: PASSED")
sys.exit(0)
